sonar.projectKey=devops-mega-project
sonar.projectName=DevOps Mega Project
sonar.sources=app
sonar.exclusions=**/node_modules/**,**/*.test.js
sonar.host.url=http://localhost:9000
sonar.qualitygate.wait=true
