apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-mega-app-monitor
  namespace: monitoring
  labels:
    release: monitoring   # must match the kube-prometheus-stack release label
spec:
  selector:
    matchLabels:
      app: devops-mega-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
