apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-mega-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:yourgithubuser/devops-mega-gitops.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true       # remove resources deleted from git
      selfHeal: true     # revert manual cluster drift back to git state
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
